// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/dashboard";
  };
  "features/dashboard/pages/DashboardPage.tsx": {
    id: "root-index";
    page: "/";
  } | {
    id: "features/dashboard/pages/DashboardPage";
    page: "/dashboard";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "root-index": typeof import("./app/features/dashboard/pages/DashboardPage.tsx");
  "features/dashboard/pages/DashboardPage": typeof import("./app/features/dashboard/pages/DashboardPage.tsx");
};